/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tp_id;


import java.io.FileReader;
import java.io.FileWriter;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLStreamConstants;
import javax.xml.stream.XMLStreamReader;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.stream.XMLOutputFactory;
import javax.xml.stream.XMLStreamWriter;
import net.sf.saxon.s9api.SaxonApiException;
import net.sf.saxon.s9api.XdmValue;
import net.sf.saxon.trans.XPathException;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jDialog2 = new javax.swing.JDialog();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jDialog3 = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jDialog4 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jDialog5 = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jDialog6 = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jDialog7 = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jDialog8 = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jDialog9 = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jDialog11 = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Ver_conteudo_XML = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Val_modelo_DTD = new javax.swing.JMenuItem();
        Val_modelo_XSD = new javax.swing.JMenuItem();
        Limpar_Output = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        adiconaAutor = new javax.swing.JMenuItem();
        eliminaAutor = new javax.swing.JMenuItem();
        AlteraAtributosAutor = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        PesAutorNome = new javax.swing.JMenuItem();
        PesAutorNac = new javax.swing.JMenuItem();
        PesObrasAutor = new javax.swing.JMenuItem();
        PesAutorPrem = new javax.swing.JMenuItem();
        PesLivrosAutora = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        fotoAutores = new javax.swing.JMenuItem();
        listagemAutores = new javax.swing.JMenuItem();
        top5Livros = new javax.swing.JMenuItem();
        fotoCapasLivro = new javax.swing.JMenuItem();
        juncaoEscritoresObras = new javax.swing.JMenuItem();

        jDialog1.setBackground(new java.awt.Color(102, 102, 102));
        jDialog1.getContentPane().setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jTextField1);
        jTextField1.setBounds(129, 77, 117, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Autor:");
        jDialog1.getContentPane().add(jLabel2);
        jLabel2.setBounds(57, 80, 60, 20);

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton1);
        jButton1.setBounds(129, 117, 117, 23);

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jDialog1.getContentPane().add(jPanel10);
        jPanel10.setBounds(-3, -4, 410, 300);

        jDialog2.getContentPane().setLayout(null);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jTextField2);
        jTextField2.setBounds(134, 102, 117, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Autor:");
        jDialog2.getContentPane().add(jLabel3);
        jLabel3.setBounds(62, 105, 60, 20);

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton2);
        jButton2.setBounds(134, 142, 117, 23);

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jDialog2.getContentPane().add(jPanel9);
        jPanel9.setBounds(-3, -4, 430, 330);

        jDialog3.getContentPane().setLayout(null);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Alterar Nascimento:");
        jDialog3.getContentPane().add(jLabel12);
        jLabel12.setBounds(22, 121, 134, 20);
        jDialog3.getContentPane().add(jTextField12);
        jTextField12.setBounds(22, 143, 115, 22);

        jButton11.setText("Alterar Nascimento");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton11);
        jButton11.setBounds(179, 143, 132, 23);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Alterar Morte:");
        jDialog3.getContentPane().add(jLabel13);
        jLabel13.setBounds(22, 184, 100, 20);
        jDialog3.getContentPane().add(jTextField13);
        jTextField13.setBounds(22, 206, 113, 22);

        jButton12.setText("Alterar Morte");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton12);
        jButton12.setBounds(179, 206, 100, 23);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Alterar Nacionalidade:");
        jDialog3.getContentPane().add(jLabel14);
        jLabel14.setBounds(22, 58, 160, 20);

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jTextField14);
        jTextField14.setBounds(22, 80, 196, 22);

        jButton13.setText("Alterar Nacionalidade");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton13);
        jButton13.setBounds(250, 80, 144, 23);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Autor");
        jDialog3.getContentPane().add(jLabel11);
        jLabel11.setBounds(22, 9, 60, 20);

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jTextField11);
        jTextField11.setBounds(101, 6, 115, 22);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Alterar Genero:");
        jDialog3.getContentPane().add(jLabel15);
        jLabel15.setBounds(22, 247, 120, 20);
        jDialog3.getContentPane().add(jTextField15);
        jTextField15.setBounds(22, 269, 113, 22);

        jButton14.setText("Alterar Genero");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton14);
        jButton14.setBounds(179, 269, 106, 23);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Alterar Ocupacao:");
        jDialog3.getContentPane().add(jLabel16);
        jLabel16.setBounds(22, 318, 130, 20);
        jDialog3.getContentPane().add(jTextField16);
        jTextField16.setBounds(22, 340, 113, 22);

        jButton15.setText("Alterar ocupacao");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton15);
        jButton15.setBounds(179, 340, 120, 23);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jDialog3.getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 420, 420);

        jDialog4.getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Autor do livro:");
        jDialog4.getContentPane().add(jLabel4);
        jLabel4.setBounds(41, 80, 100, 20);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton3.setText("Adicionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jDialog4.getContentPane().add(jPanel2);
        jPanel2.setBounds(-3, -4, 410, 300);

        jDialog5.getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Isbn da obra:");
        jDialog5.getContentPane().add(jLabel5);
        jLabel5.setBounds(58, 105, 90, 20);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton4)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jDialog5.getContentPane().add(jPanel3);
        jPanel3.setBounds(1, -3, 400, 300);

        jDialog6.getContentPane().setLayout(null);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Alterar Titulo:");
        jDialog6.getContentPane().add(jLabel17);
        jLabel17.setBounds(22, 121, 100, 20);
        jDialog6.getContentPane().add(jTextField17);
        jTextField17.setBounds(22, 143, 115, 22);

        jButton16.setText("Alterar Titulo");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton16);
        jButton16.setBounds(179, 143, 98, 23);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Alterar Editora:");
        jDialog6.getContentPane().add(jLabel18);
        jLabel18.setBounds(22, 184, 110, 20);
        jDialog6.getContentPane().add(jTextField18);
        jTextField18.setBounds(22, 206, 113, 22);

        jButton17.setText("Alterar Editora");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton17);
        jButton17.setBounds(179, 206, 105, 23);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Alterar Nome Autor:");
        jDialog6.getContentPane().add(jLabel19);
        jLabel19.setBounds(22, 58, 150, 20);

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jTextField19);
        jTextField19.setBounds(22, 80, 191, 22);

        jButton18.setText("Alterar Nome Autor");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton18);
        jButton18.setBounds(245, 80, 134, 23);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ISBN");
        jDialog6.getContentPane().add(jLabel20);
        jLabel20.setBounds(22, 9, 50, 20);

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jTextField20);
        jTextField20.setBounds(96, 6, 115, 22);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Alterar Preco:");
        jDialog6.getContentPane().add(jLabel21);
        jLabel21.setBounds(22, 247, 100, 20);
        jDialog6.getContentPane().add(jTextField21);
        jTextField21.setBounds(22, 269, 113, 22);

        jButton19.setText("Alterar Preco");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton19);
        jButton19.setBounds(179, 269, 98, 23);

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        jDialog6.getContentPane().add(jPanel5);
        jPanel5.setBounds(-3, -4, 400, 330);

        jDialog7.getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome:");
        jDialog7.getContentPane().add(jLabel6);
        jLabel6.setBounds(75, 106, 49, 20);
        jDialog7.getContentPane().add(jTextField5);
        jTextField5.setBounds(136, 103, 117, 22);

        jButton5.setText("Pesquisar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jDialog7.getContentPane().add(jButton5);
        jButton5.setBounds(136, 143, 117, 23);

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jDialog7.getContentPane().add(jPanel6);
        jPanel6.setBounds(-3, -4, 540, 590);

        jDialog8.getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nacionalidade");
        jDialog8.getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 100, 100, 20);
        jDialog8.getContentPane().add(jTextField6);
        jTextField6.setBounds(132, 97, 117, 22);

        jButton6.setText("Pesquisar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jDialog8.getContentPane().add(jButton6);
        jButton6.setBounds(132, 137, 117, 23);

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jDialog8.getContentPane().add(jPanel7);
        jPanel7.setBounds(-3, -4, 540, 570);

        jDialog9.getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Autor");
        jDialog9.getContentPane().add(jLabel8);
        jLabel8.setBounds(82, 114, 50, 20);
        jDialog9.getContentPane().add(jTextField7);
        jTextField7.setBounds(144, 111, 117, 22);

        jButton7.setText("Pesquisar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jDialog9.getContentPane().add(jButton7);
        jButton7.setBounds(144, 151, 117, 23);

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jDialog9.getContentPane().add(jPanel8);
        jPanel8.setBounds(-3, -4, 580, 520);

        jDialog11.getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nome do Autor");
        jDialog11.getContentPane().add(jLabel10);
        jLabel10.setBounds(38, 97, 120, 27);

        jButton9.setText("Pesquisar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jDialog11.getContentPane().add(jButton9);
        jButton9.setBounds(152, 162, 80, 23);
        jDialog11.getContentPane().add(jTextField8);
        jTextField8.setBounds(176, 99, 138, 22);

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jDialog11.getContentPane().add(jPanel12);
        jPanel12.setBounds(-3, -4, 580, 520);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Output");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jMenu1.setText("Opções");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Ver_conteudo_XML.setText("Ver conteúdo XML autor");
        Ver_conteudo_XML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_conteudo_XMLActionPerformed(evt);
            }
        });
        jMenu1.add(Ver_conteudo_XML);

        jMenuItem4.setText("Ver conteúdo XML livro");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        Val_modelo_DTD.setText("Validar modelo de dados DTD");
        Val_modelo_DTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Val_modelo_DTDActionPerformed(evt);
            }
        });
        jMenu1.add(Val_modelo_DTD);

        Val_modelo_XSD.setText("Validar modelo de dados XSD");
        Val_modelo_XSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Val_modelo_XSDActionPerformed(evt);
            }
        });
        jMenu1.add(Val_modelo_XSD);

        Limpar_Output.setText("Limpar Output");
        Limpar_Output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpar_OutputActionPerformed(evt);
            }
        });
        jMenu1.add(Limpar_Output);

        Sair.setText("Sair da aplicação");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        jMenu1.add(Sair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Alterar dados do modelo XML");

        adiconaAutor.setText("Adicionar autor");
        adiconaAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adiconaAutorActionPerformed(evt);
            }
        });
        jMenu2.add(adiconaAutor);

        eliminaAutor.setText("Eliminar autor");
        eliminaAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaAutorActionPerformed(evt);
            }
        });
        jMenu2.add(eliminaAutor);

        AlteraAtributosAutor.setText("Alterar atributos de um autor");
        AlteraAtributosAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlteraAtributosAutorActionPerformed(evt);
            }
        });
        jMenu2.add(AlteraAtributosAutor);

        jMenuItem1.setText("Adicionar Livro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Eliminar Livro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Alterar atributos de um livro");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Efetuar pesquisas XPATH");

        PesAutorNome.setText("Pesquisa autores pelo nome");
        PesAutorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesAutorNomeActionPerformed(evt);
            }
        });
        jMenu3.add(PesAutorNome);

        PesAutorNac.setText("Pesquisar autores por nacionalidade");
        PesAutorNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesAutorNacActionPerformed(evt);
            }
        });
        jMenu3.add(PesAutorNac);

        PesObrasAutor.setText("Pesquisar obras de determinado autor");
        PesObrasAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesObrasAutorActionPerformed(evt);
            }
        });
        jMenu3.add(PesObrasAutor);

        PesAutorPrem.setText("Qual o autor mais premiado?");
        PesAutorPrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesAutorPremActionPerformed(evt);
            }
        });
        jMenu3.add(PesAutorPrem);

        PesLivrosAutora.setText("Quais os livros de determinada autora (acima de x valor)");
        PesLivrosAutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesLivrosAutoraActionPerformed(evt);
            }
        });
        jMenu3.add(PesLivrosAutora);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Gerar Outputs");

        fotoAutores.setText("HTML de fotos dos autores");
        fotoAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotoAutoresActionPerformed(evt);
            }
        });
        jMenu4.add(fotoAutores);

        listagemAutores.setText("TXT da listagem de todos os autores");
        listagemAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listagemAutoresActionPerformed(evt);
            }
        });
        jMenu4.add(listagemAutores);

        top5Livros.setText("XML dos 5 livros mais caros");
        top5Livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                top5LivrosActionPerformed(evt);
            }
        });
        jMenu4.add(top5Livros);

        fotoCapasLivro.setText("HTML das capas dos livros de determinado autor");
        fotoCapasLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotoCapasLivroActionPerformed(evt);
            }
        });
        jMenu4.add(fotoCapasLivro);

        juncaoEscritoresObras.setText("XML - Junção da informação dos escritores e suas obras");
        juncaoEscritoresObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juncaoEscritoresObrasActionPerformed(evt);
            }
        });
        jMenu4.add(juncaoEscritoresObras);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ver_conteudo_XMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_conteudo_XMLActionPerformed
         Document doc = XMLJDomFunctions.lerDocumentoXML("escritores.xml");

        if (doc == null) {
            JOptionPane.showMessageDialog(this, "Ficheiro XML não existe!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String texto = XMLJDomFunctions.escreverDocumentoString(doc);
            output.setText(texto);
        }
    }//GEN-LAST:event_Ver_conteudo_XMLActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void fotoCapasLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotoCapasLivroActionPerformed
        // TODO add your handling code here:
        jDialog11.setTitle("Capas dos livros");
        jDialog11.setSize(400, 300);
        jDialog11.setLocation(50, 50);
        jDialog11.setVisible(true);
    }//GEN-LAST:event_fotoCapasLivroActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void adiconaAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adiconaAutorActionPerformed
        // TODO add your handling code here:
        jDialog1.setTitle("Adicionar Autor");
        jDialog1.setSize(400, 300);
        jDialog1.setLocation(50, 50);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_adiconaAutorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        try {
            // TODO add your handling code here:
            String lista = jTextField1.getText();
            String[] campos = lista.split(", ");
            String nomeAutor = jTextField1.getText();
            Autor x = null;




                x = Wrapper.criaAutor(nomeAutor);
                Document doc = XMLJDomFunctions.lerDocumentoXML("escritores.xml");
                doc = XMLFunctions.adicionaAutor(x, doc);

                if (doc != null) {
                    XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "escritores.xml");
                    JOptionPane.showMessageDialog(this,
                            "Autor adicionada com sucesso",
                            "Informação", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(this,
                            "Autor já existe no ficheiro",
                            "Informação", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,
                        "Erro ao adicionar autor",
                        "Informação", JOptionPane.INFORMATION_MESSAGE);
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
            jDialog1.setVisible(false);
            jTextField1.setText(" ");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Limpar_OutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpar_OutputActionPerformed
        // TODO add your handling code here:
        output.setText("");
    }//GEN-LAST:event_Limpar_OutputActionPerformed

    private void Val_modelo_DTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Val_modelo_DTDActionPerformed
        try {
            int res = JDOMFunctionsValidate.validarDocumentoDTD("escritores.xml", "escritores.dtd");

            if (res == 1) {
                JOptionPane.showMessageDialog(this, "O Ficheiro é válido por DTD.", "Validação", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "O Ficheiro não é válido por DTD", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JDOMException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Val_modelo_DTDActionPerformed

    private void Val_modelo_XSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Val_modelo_XSDActionPerformed
       if (JDOMFunctionsValidate.validarDocumentoXSD("escritores.xml", "escritores.xsd") == 1) {
            JOptionPane.showMessageDialog(this, "escritores.xml validado por XSD", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "escritores.xml invalido por XSD", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Val_modelo_XSDActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jDialog4.setTitle("Adicionar Livro");
        jDialog4.setSize(400, 300);
        jDialog4.setLocation(50, 50);
        jDialog4.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("escritores.xml");
        doc = XMLFunctions.eliminaAutor(jTextField2.getText(), doc);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "escritores.xml");
            JOptionPane.showMessageDialog(this, "Autor eliminado com sucesso");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao eliminar autor");
        }
        jDialog2.setVisible(false);
        jTextField2.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void eliminaAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaAutorActionPerformed
       jDialog2.setTitle("Eliminar Autor");
        jDialog2.setSize(400, 300);
        jDialog2.setLocation(50, 50);
        jDialog2.setVisible(true);
    }//GEN-LAST:event_eliminaAutorActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:

        Document doc = XMLJDomFunctions.lerDocumentoXML("escritores.xml");
        doc = XMLFunctions.alteraNascimento(jTextField11.getText(), jTextField12.getText(), doc);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "escritores.xml");
            JOptionPane.showMessageDialog(this, "O nascimento do escritor " + jTextField11.getText() + " foi alterado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao tentar alterar o nascimento do escritor " + jTextField11.getText() + "!");

        }
        jDialog3.setVisible(false);
        jTextField12.setText(" ");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:

        Document doc = XMLJDomFunctions.lerDocumentoXML("escritores.xml");
        doc = XMLFunctions.alteraMorte(jTextField11.getText(), jTextField13.getText(), doc);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "escritores.xml");
            JOptionPane.showMessageDialog(this, "A morte de " + jTextField11.getText() + " foi alterado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao tentar alterar a morte de " + jTextField11.getText() + "!");
        }
        jDialog3.setVisible(false);
        jTextField13.setText(" ");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:

        Document doc = XMLJDomFunctions.lerDocumentoXML("escritores.xml");
        doc = XMLFunctions.alteraNacionalidade(jTextField11.getText(), jTextField14.getText(), doc);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "escritores.xml");
            JOptionPane.showMessageDialog(this, "Nacionalidade do escritor " + jTextField11.getText() + " foi alterado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao tentar alterar a nacionalidade do escritor " + jTextField11.getText() + "!");

        }
        jDialog3.setVisible(false);
        jTextField14.setText(" ");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       Document doc = XMLJDomFunctions.lerDocumentoXML("escritores.xml");
        doc = XMLFunctions.alteraGenero(jTextField11.getText(), jTextField15.getText(), doc);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "escritores.xml");
            JOptionPane.showMessageDialog(this, "Genero do autor " + jTextField11.getText() + " foi alterado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao tentar alterar o genero do autor " + jTextField11.getText() + "!");

        }
        jDialog3.setVisible(false);
        jTextField15.setText(" ");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("escritores.xml");
        doc = XMLFunctions.alteraOcupacao(jTextField11.getText(), jTextField16.getText(), doc);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "escritores.xml");
            JOptionPane.showMessageDialog(this, "Ocupacao do autor " + jTextField11.getText() + " foi alterado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao tentar alterar o Ocupacao do autor " + jTextField11.getText() + "!");

        }
        jDialog3.setVisible(false);
        jTextField16.setText(" ");

        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void AlteraAtributosAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlteraAtributosAutorActionPerformed
        jDialog3.setTitle("Editar Autor");
        jDialog3.setSize(400, 412);
        jDialog3.setLocation(50, 50);
        jDialog3.setVisible(true);
    }//GEN-LAST:event_AlteraAtributosAutorActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("obras.xml");

        if (doc == null) {
            JOptionPane.showMessageDialog(this, "Ficheiro XML não existe!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String texto = XMLJDomFunctions.escreverDocumentoString(doc);
            output.setText(texto);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            String lista = jTextField3.getText();
            String[] campos = lista.split(", ");
            String nomeAutor = jTextField3.getText();
            Obra x = null;

                x = Wrapper.criaObra(nomeAutor);
                Document doc = XMLJDomFunctions.lerDocumentoXML("obras.xml");
                doc = XMLFunctions.adicionaObra(x, doc);

                if (doc != null) {
                    XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "obras.xml");
                    JOptionPane.showMessageDialog(this,
                            "Livro adicionada com sucesso",
                            "Informação", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(this,
                            "Livro já existe no ficheiro",
                            "Informação", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this,
                        "Erro ao adicionar autor",
                        "Informação", JOptionPane.INFORMATION_MESSAGE);
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
            jDialog4.setVisible(false);
            jTextField3.setText(" ");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         Document doc = XMLJDomFunctions.lerDocumentoXML("obras.xml");
        doc = XMLFunctions.eliminaObra(jTextField4.getText(), doc);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "obras.xml");
            JOptionPane.showMessageDialog(this, "Obra eliminada com sucesso");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao eliminar obra");
        }
        jDialog5.setVisible(false);
        jTextField2.setText(" ");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       jDialog5.setTitle("Eliminar Obra");
        jDialog5.setSize(400, 300);
        jDialog5.setLocation(50, 50);
        jDialog5.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       jDialog6.setTitle("Editar Autor");
        jDialog6.setSize(391, 350);
        jDialog6.setLocation(50, 50);
        jDialog6.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("obras.xml");
        doc = XMLFunctions.alteraTitulo(jTextField20.getText(), jTextField17.getText(), doc);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "obras.xml");
            JOptionPane.showMessageDialog(this, "Titulo da obra  " + jTextField20.getText() + " foi alterado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao tentar alterar o Titulo da obra " + jTextField20.getText() + "!");

        }
        jDialog6.setVisible(false);
        jTextField17.setText(" ");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
       Document doc = XMLJDomFunctions.lerDocumentoXML("obras.xml");
        doc = XMLFunctions.alteraEditora(jTextField20.getText(), jTextField18.getText(), doc);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "obras.xml");
            JOptionPane.showMessageDialog(this, "Editora da obra  " + jTextField20.getText() + " foi alterado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao tentar alterar a Editora da obra " + jTextField20.getText() + "!");

        }
        jDialog6.setVisible(false);
        jTextField18.setText(" ");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
       Document doc = XMLJDomFunctions.lerDocumentoXML("obras.xml");
        doc = XMLFunctions.alteraNomeAutor(jTextField20.getText(), jTextField19.getText(), doc);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "obras.xml");
            JOptionPane.showMessageDialog(this, "Nome do autor da obra  " + jTextField20.getText() + " foi alterado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao tentar alterar o Nome do autor da obra " + jTextField20.getText() + "!");

        }
        jDialog6.setVisible(false);
        jTextField19.setText(" ");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        Document doc = XMLJDomFunctions.lerDocumentoXML("obras.xml");
        doc = XMLFunctions.alteraPreco(jTextField20.getText(), jTextField21.getText(), doc);

        if (doc != null) {
            XMLJDomFunctions.escreverDocumentoParaFicheiro(doc, "obras.xml");
            JOptionPane.showMessageDialog(this, "Preco da obra  " + jTextField20.getText() + " foi alterado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao tentar alterar o Preco da obra " + jTextField20.getText() + "!");

        }
        jDialog6.setVisible(false);
        jTextField21.setText(" ");
    }//GEN-LAST:event_jButton19ActionPerformed

    private void PesAutorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesAutorNomeActionPerformed
        jDialog7.setTitle("Pesquisar Autor");
        jDialog7.setSize(400, 400);
        jDialog7.setLocation(50, 50);
        jDialog7.setVisible(true);
    }//GEN-LAST:event_PesAutorNomeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            Scanner ler = new Scanner(System.in);
            String valor = jTextField5.getText();
            StringBuilder texto = new StringBuilder();
            texto = texto.append("Autor: ").append(jTextField5.getText()).append("\n\n");
            ArrayList<String> xpath = new ArrayList<>();

            xpath.add("//autor[contains(@nome,'" + valor + "')]/@id");
            xpath.add("//autor[contains(@nome,'" + valor + "')]/Dados/nacionalidade");
            xpath.add("//autor[contains(@nome,'" + valor + "')]/Dados/nascimento");
            xpath.add("//autor[contains(@nome,'" + valor + "')]/Dados/morte");
            xpath.add("//autor[contains(@nome,'" + valor + "')]/Dados/genero");
            xpath.add("//autor[contains(@nome,'" + valor + "')]/Dados/ocupacao");
            xpath.add("//autor[contains(@nome,'" + valor + "')]/Dados/foto");

            for (int i = 0; i < xpath.size(); i++) {
                XdmValue res2 = XPathFunctions.executaXpath(xpath.get(i), "escritores.xml");
                if (res2 == null) {
                    output.setText("Ficheiro XML não existe.");
                }
                String s2 = XPathFunctions.listaResultado(res2);
                if (i == 0) {
                    texto = texto.append("Id: ").append(s2).append("\n");
                }
                if (i == 1) {
                    texto = texto.append("Nacionalidade: ").append(s2).append("\n");
                }
                if (i == 2) {
                    texto = texto.append("Nascimento: ").append(s2).append("\n");
                }
                if (i == 3) {
                    texto = texto.append("Morte: ").append(s2).append("\n");
                }
                if (i == 4) {
                    texto = texto.append("Genero: ").append(s2).append("\n");
                }
                if (i == 5) {
                    texto = texto.append("Ocupacao: ").append(s2).append("\n");
                }
                if (i == 6) {
                    texto = texto.append("Foto: ").append(s2).append("\n");
                }
            }

            if (xpath.isEmpty()) {
                output.setText("Pesquisa sem informação");
            } else {
                output.setText(texto.toString());
            }
            jDialog7.setVisible(false);
            jTextField5.setText(" ");
        } catch (SaxonApiException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            Scanner ler = new Scanner(System.in);
            System.out.println("Introduza palavra de pesquisa");
            String xp = null;
            String valor = jTextField6.getText();

            xp = "//autor/Dados[contains(nacionalidade,'" + valor + "')]/../@nome";

            XdmValue res = XPathFunctions.executaXpath(xp, "escritores.xml");
            String x = XPathFunctions.listaResultado(res);

            if (res == null) {
                output.setText("Ficheiro nao existe");
            } else if (res.size() == 0) {
                output.setText("Pesquisa sem informação");
            } else {
                output.setText(x);
            }
            jDialog8.setVisible(false);
            jTextField6.setText(" ");
        } catch (SaxonApiException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void PesAutorNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesAutorNacActionPerformed
        jDialog8.setTitle("Pesquisar Autor pela nacionalidade");
        jDialog8.setSize(400, 400);
        jDialog8.setLocation(50, 50);
        jDialog8.setVisible(true);
    }//GEN-LAST:event_PesAutorNacActionPerformed

    private void PesObrasAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesObrasAutorActionPerformed
        jDialog9.setTitle("Pesquisar obras pelo autor");
        jDialog9.setSize(400, 400);
        jDialog9.setLocation(50, 50);
        jDialog9.setVisible(true);
    }//GEN-LAST:event_PesObrasAutorActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            Scanner ler = new Scanner(System.in);
            System.out.println("Introduza palavra de pesquisa");
            String xp = null;
            String valor = jTextField7.getText();

            xp = "//obra/Dados[contains(nomeautor,'" + valor + "')]/titulo";

            XdmValue res = XPathFunctions.executaXpath(xp, "obras.xml");
            String x = XPathFunctions.listaResultado(res);

            if (res == null) {
                output.setText("Ficheiro nao existe");
            } else if (res.size() == 0) {
                output.setText("Pesquisa sem informação");
            } else {
                output.setText(x);
            }
            jDialog9.setVisible(false);
            jTextField7.setText(" ");
        } catch (SaxonApiException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void top5LivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top5LivrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_top5LivrosActionPerformed

    private void juncaoEscritoresObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juncaoEscritoresObrasActionPerformed
        String xmlFilePath1 = "escritores.xml";
        String xmlFilePath2 = "obras.xml";
        String combinedXmlFilePath = "juncao.xml";

        try {
            // Create a FileReader for the first XML file
            FileReader fileReader1 = new FileReader(xmlFilePath1);

            // Create a FileReader for the second XML file
            FileReader fileReader2 = new FileReader(xmlFilePath2);

            // Create an XMLInputFactory
            XMLInputFactory inputFactory = XMLInputFactory.newInstance();

            // Create an XMLStreamReader for the first XML file
            XMLStreamReader reader1 = inputFactory.createXMLStreamReader(fileReader1);

            // Create an XMLStreamReader for the second XML file
            XMLStreamReader reader2 = inputFactory.createXMLStreamReader(fileReader2);

            // Create an XMLOutputFactory
            XMLOutputFactory outputFactory = XMLOutputFactory.newInstance();

            // Create an XMLStreamWriter for the combined XML file
            XMLStreamWriter writer = outputFactory.createXMLStreamWriter(new FileWriter(combinedXmlFilePath));

            // Start the combined XML document
            writer.writeStartDocument();
            writer.writeStartElement("Feito");

            // Copy the root element of the first XML file
            copyElement(reader1, writer);

            // Copy the root element of the second XML file
            copyElement(reader2, writer);

            // Close the combined XML document
            writer.writeEndElement();
            writer.writeEndDocument();
            writer.close();

            // Close the XML stream readers
            reader1.close();
            reader2.close();

            System.out.println("Ficheiros de XML juntos.");
            output.setText("Ficheiros de XML juntos.");
        } catch (Exception e) {
            System.err.println("Erro a criar ficheiro xml: " + e.getMessage());
        }
}
//GEN-LAST:event_juncaoEscritoresObrasActionPerformed

    private void fotoAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotoAutoresActionPerformed
        // TODO add your handling code here:
        try {

            SaxonFunctionsXQuery.xQueryToHtml("fotosAut.html", "transf_html.xql");
        } catch (XPathException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this,
                "Transformação feita com sucesso... a abrir browser...",
                "XQuery para HTML", JOptionPane.INFORMATION_MESSAGE);
        String url = "fotosAut.html";
        File htmlFile = new File(url);
        try {
            Desktop.getDesktop().browse(htmlFile.toURI());
        } catch (IOException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fotoAutoresActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Element raiz = new Element("autor");
        Document docV = new Document(raiz);
        raiz.addContent(jTextField8.getText());
        XMLJDomFunctions.escreverDocumentoParaFicheiro(docV, "capa.xml");
        try {
            try {
                SaxonFunctionsXQuery.xQueryToHtml("fotoCapas.html", "transfToHTML4.xql");
            } catch (IOException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this,
                    "Transformação feita com sucesso... a abrir browser...",
                    "XSLT para HTML", JOptionPane.INFORMATION_MESSAGE);
            String url = "fotoCapas.html";
            File htmlFile = new File(url);
            JOptionPane.showMessageDialog(null, "Ficheiro HTML Criado", "XML to HTML", JOptionPane.INFORMATION_MESSAGE);
            jDialog9.setVisible(false);
            jTextField8.setText(" ");
            try {
                Desktop.getDesktop().browse(htmlFile.toURI());
            } catch (IOException ex) {
                Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (XPathException ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);

    }                             
    }//GEN-LAST:event_jButton9ActionPerformed

    private void listagemAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listagemAutoresActionPerformed

        String xmlFilePath = "escritores.xml";
        String txtFilePath = "escritoresdoxml.txt";

        try {
            // Create a FileReader to read the XML file
            FileReader fileReader = new FileReader(xmlFilePath);

            // Create an XMLInputFactory
            XMLInputFactory factory = XMLInputFactory.newInstance();

            // Create an XMLStreamReader from the XMLInputFactory
            XMLStreamReader reader = factory.createXMLStreamReader(fileReader);

            // Create a FileWriter to write the text content to the output file
            FileWriter writer = new FileWriter(txtFilePath);

            // Read the XML file and extract the text content
            while (reader.hasNext()) {
                int eventType = reader.next();
                if (eventType == XMLStreamConstants.CHARACTERS) {
                    String text = reader.getText().trim();
                    if (!text.isEmpty()) {
                        writer.write(text);
                        writer.write(System.lineSeparator());
                    }
                }
            }

            // Close the reader and writer
            reader.close();
            writer.close();

            System.out.println("XML para TXT com sucesso.");
        } catch (Exception e) {
            System.err.println("Erro a converter XML para TXT: " + e.getMessage());
        }
        output.setText(" ");
        try {
            // Create a FileReader to read the text file
            FileReader fileReader = new FileReader(txtFilePath);

            // Create a BufferedReader to read the text file efficiently
            BufferedReader reader = new BufferedReader(fileReader);

            String line;
            while ((line = reader.readLine()) != null) {
                output.setText("Ficheiro TXT criado");
            }

            // Close the reader
            reader.close();
        } catch (Exception e) {
            System.err.println("Error displaying TXT file: " + e.getMessage());
        }

    }//GEN-LAST:event_listagemAutoresActionPerformed

    private void PesAutorPremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesAutorPremActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesAutorPremActionPerformed

    private void PesLivrosAutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesLivrosAutoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesLivrosAutoraActionPerformed
private static void copyElement(XMLStreamReader reader, XMLStreamWriter writer) throws Exception {
        int depth = 0;
        int eventType;
        while (reader.hasNext()) {
            eventType = reader.next();
            switch (eventType) {
                case XMLStreamReader.START_ELEMENT:
                    depth++;
                    writer.writeStartElement(reader.getLocalName());
                    for (int i = 0; i < reader.getAttributeCount(); i++) {
                        writer.writeAttribute(reader.getAttributeLocalName(i), reader.getAttributeValue(i));
                    }
                    break;
                case XMLStreamReader.END_ELEMENT:
                    depth--;
                    writer.writeEndElement();
                    if (depth == 0) {
                        return;
                    }
                    break;
                case XMLStreamReader.CHARACTERS:
                    writer.writeCharacters(reader.getText());
                    break;
                case XMLStreamReader.CDATA:
                    writer.writeCData(reader.getText());
                    break;
                default:
                    break;
            }
        }
           }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlteraAtributosAutor;
    private javax.swing.JMenuItem Limpar_Output;
    private javax.swing.JMenuItem PesAutorNac;
    private javax.swing.JMenuItem PesAutorNome;
    private javax.swing.JMenuItem PesAutorPrem;
    private javax.swing.JMenuItem PesLivrosAutora;
    private javax.swing.JMenuItem PesObrasAutor;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem Val_modelo_DTD;
    private javax.swing.JMenuItem Val_modelo_XSD;
    private javax.swing.JMenuItem Ver_conteudo_XML;
    private javax.swing.JMenuItem adiconaAutor;
    private javax.swing.JMenuItem eliminaAutor;
    private javax.swing.JMenuItem fotoAutores;
    private javax.swing.JMenuItem fotoCapasLivro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog11;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JDialog jDialog7;
    private javax.swing.JDialog jDialog8;
    private javax.swing.JDialog jDialog9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JMenuItem juncaoEscritoresObras;
    private javax.swing.JMenuItem listagemAutores;
    private javax.swing.JTextArea output;
    private javax.swing.JMenuItem top5Livros;
    // End of variables declaration//GEN-END:variables
}
